# Generated by Django 3.2.13 on 2023-09-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('diretor', models.CharField(max_length=70)),
                ('genero', models.CharField(max_length=20)),
                ('lancamento', models.DateField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=70)),
                ('jogabilidade', models.CharField(choices=[('L', 'Local'), ('O', 'Online'), ('A', 'Ambos')], max_length=1)),
                ('genero', models.CharField(choices=[('S', 'Shooter'), ('E', 'Esporte'), ('H', 'História'), ('A', 'Arcade')], max_length=4)),
                ('lancamento', models.DateField(max_length=50)),
            ],
        ),
    ]
